package atlas.cool.summary.model;

// Generated Jul 11, 2013 5:02:12 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CoolIovRanges generated by hbm2java.
 */
@Entity
@Table(name = "COOL_IOV_RANGES", schema = "ATLAS_COND_TOOLS")
@SequenceGenerator(name = "COOLIOVRANGE_SEQ", sequenceName = "COOLIOVRANGE_SEQ", allocationSize = 1)
public class CoolIovRanges implements java.io.Serializable {

	private BigDecimal coolIovrangePk;
	private CoolIovSummary coolIovSummary;
	private BigDecimal coolIovrangeSince;
	private BigDecimal coolIovrangeUntil;
	private BigDecimal coolIovrangeNiovs;
	private String coolIovrangeIshole;
	private String coolIovbase;
	private String coolIovsinceStr;
	private String coolIovuntilStr;

	public CoolIovRanges() {
	}

	public CoolIovRanges(final BigDecimal coolIovrangePk,
			final CoolIovSummary coolIovSummary, final BigDecimal coolIovrangeSince,
			final BigDecimal coolIovrangeUntil) {
		this.coolIovrangePk = coolIovrangePk;
		this.coolIovSummary = coolIovSummary;
		this.coolIovrangeSince = coolIovrangeSince;
		this.coolIovrangeUntil = coolIovrangeUntil;
	}

	public CoolIovRanges(final BigDecimal coolIovrangePk,
			final CoolIovSummary coolIovSummary, final BigDecimal coolIovrangeSince,
			final BigDecimal coolIovrangeUntil, final BigDecimal coolIovrangeNiovs,
			final String coolIovrangeIshole, final String coolIovbase,
			final String coolIovsinceStr, final String coolIovuntilStr) {
		this.coolIovrangePk = coolIovrangePk;
		this.coolIovSummary = coolIovSummary;
		this.coolIovrangeSince = coolIovrangeSince;
		this.coolIovrangeUntil = coolIovrangeUntil;
		this.coolIovrangeNiovs = coolIovrangeNiovs;
		this.coolIovrangeIshole = coolIovrangeIshole;
		this.coolIovbase = coolIovbase;
		this.coolIovsinceStr = coolIovsinceStr;
		this.coolIovuntilStr = coolIovuntilStr;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "COOLIOVRANGE_SEQ")
	@Column(name = "COOL_IOVRANGE_PK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangePk() {
		return coolIovrangePk;
	}

	public void setCoolIovrangePk(final BigDecimal coolIovrangePk) {
		this.coolIovrangePk = coolIovrangePk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COOL_IOVSUMMARY_FK", nullable = false)
	public CoolIovSummary getCoolIovSummary() {
		return coolIovSummary;
	}

	public void setCoolIovSummary(final CoolIovSummary coolIovSummary) {
		this.coolIovSummary = coolIovSummary;
	}

	@Column(name = "COOL_IOVRANGE_SINCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeSince() {
		return coolIovrangeSince;
	}

	public void setCoolIovrangeSince(final BigDecimal coolIovrangeSince) {
		this.coolIovrangeSince = coolIovrangeSince;
	}

	@Column(name = "COOL_IOVRANGE_UNTIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeUntil() {
		return coolIovrangeUntil;
	}

	public void setCoolIovrangeUntil(final BigDecimal coolIovrangeUntil) {
		this.coolIovrangeUntil = coolIovrangeUntil;
	}

	@Column(name = "COOL_IOVRANGE_NIOVS", precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeNiovs() {
		return coolIovrangeNiovs;
	}

	public void setCoolIovrangeNiovs(final BigDecimal coolIovrangeNiovs) {
		this.coolIovrangeNiovs = coolIovrangeNiovs;
	}

	@Column(name = "COOL_IOVRANGE_ISHOLE", length = 20)
	public String getCoolIovrangeIshole() {
		return coolIovrangeIshole;
	}

	public void setCoolIovrangeIshole(final String coolIovrangeIshole) {
		this.coolIovrangeIshole = coolIovrangeIshole;
	}

	@Column(name = "COOL_IOVBASE", length = 20)
	public String getCoolIovbase() {
		return coolIovbase;
	}

	public void setCoolIovbase(final String coolIovbase) {
		this.coolIovbase = coolIovbase;
	}

	@Column(name = "COOL_IOVSINCE_STR")
	public String getCoolIovsinceStr() {
		return coolIovsinceStr;
	}

	public void setCoolIovsinceStr(final String coolIovsinceStr) {
		this.coolIovsinceStr = coolIovsinceStr;
	}

	@Column(name = "COOL_IOVUNTIL_STR")
	public String getCoolIovuntilStr() {
		return coolIovuntilStr;
	}

	public void setCoolIovuntilStr(final String coolIovuntilStr) {
		this.coolIovuntilStr = coolIovuntilStr;
	}

}
