package atlas.cool.summary.model;

// Generated Jul 11, 2013 5:02:12 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import atlas.cool.annotations.CoolQuery;

/**
 * CoolIovRanges generated by hbm2java.
 */
@Entity
@Table(name = "COOL_IOV_RANGES", schema = "ATLAS_COND_TOOLS")
@SequenceGenerator(name = "COOLIOVRANGE_SEQ", sequenceName = "COOLIOVRANGE_SEQ", allocationSize = 1)
@NamedQueries({
		@NamedQuery(name = CoolIovRanges.QUERY_FIND_RANGESFORCHANNEL, query = " "
				+ " from CoolIovRanges crange where crange.coolIovSummary.coolIovsummaryId = :iovsummid"),
		@NamedQuery(name = CoolIovRanges.QUERY_FIND_RANGESFORCHANNEL_ATTIME, query = " "
				+ " from CoolIovRanges crange where crange.coolIovSummary.coolIovsummaryId = :iovsummid "
				+ " and crange.coolIovrangeSince=:since"),
		@NamedQuery(name = CoolIovRanges.QUERY_FIND_RANGESFORNODE, query = " "
				+ " from CoolIovRanges crange where crange.coolIovSummary.coolNodeFullpath = :node "
				+ " and crange.coolIovSummary.schemaName=:schema and crange.coolIovSummary.db=:db") })
public class CoolIovRanges implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6690235509457263139L;
	private BigDecimal coolIovrangePk;
	private CoolIovSummary coolIovSummary;
	private BigDecimal coolIovrangeSince;
	private BigDecimal coolIovrangeUntil;
	private BigDecimal coolIovrangeNiovs;
	private Boolean coolIovrangeIshole;
	private String coolIovbase;
	private String coolIovsinceStr;
	private String coolIovuntilStr;
	private BigDecimal comaRunMin;
	private BigDecimal comaRunMax;
	private Date comaRunStartTime;
	private Date comaRunEndTime;

	@CoolQuery(name = "cool.findrangesforchannel", params = "iovsummid")
	public static final String QUERY_FIND_RANGESFORCHANNEL = "cool.findrangesforchannel";
	@CoolQuery(name = "cool.findrangesforchannel_attime", params = "iovsummid;since")
	public static final String QUERY_FIND_RANGESFORCHANNEL_ATTIME = "cool.findrangesforchannel_attime";
	@CoolQuery(name = "cool.findrangesfornode", params = "schema;db;node")
	public static final String QUERY_FIND_RANGESFORNODE = "cool.findrangesfornode";

	/**
	 * 
	 */
	public CoolIovRanges() {
	}

	/**
	 * @param coolIovrangePk
	 * @param coolIovSummary
	 * @param coolIovrangeSince
	 * @param coolIovrangeUntil
	 */
	public CoolIovRanges(final BigDecimal coolIovrangePk,
			final CoolIovSummary coolIovSummary, final BigDecimal coolIovrangeSince,
			final BigDecimal coolIovrangeUntil) {
		this.coolIovrangePk = coolIovrangePk;
		this.coolIovSummary = coolIovSummary;
		this.coolIovrangeSince = coolIovrangeSince;
		this.coolIovrangeUntil = coolIovrangeUntil;
	}

	/**
	 * @param coolIovrangePk
	 * @param coolIovSummary
	 * @param coolIovrangeSince
	 * @param coolIovrangeUntil
	 * @param coolIovrangeNiovs
	 * @param coolIovrangeIshole
	 * @param coolIovbase
	 * @param coolIovsinceStr
	 * @param coolIovuntilStr
	 */
	public CoolIovRanges(final BigDecimal coolIovrangePk,
			final CoolIovSummary coolIovSummary, final BigDecimal coolIovrangeSince,
			final BigDecimal coolIovrangeUntil, final BigDecimal coolIovrangeNiovs,
			final Boolean coolIovrangeIshole, final String coolIovbase,
			final String coolIovsinceStr, final String coolIovuntilStr) {
		this.coolIovrangePk = coolIovrangePk;
		this.coolIovSummary = coolIovSummary;
		this.coolIovrangeSince = coolIovrangeSince;
		this.coolIovrangeUntil = coolIovrangeUntil;
		this.coolIovrangeNiovs = coolIovrangeNiovs;
		this.coolIovrangeIshole = coolIovrangeIshole;
		this.coolIovbase = coolIovbase;
		this.coolIovsinceStr = coolIovsinceStr;
		this.coolIovuntilStr = coolIovuntilStr;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "COOLIOVRANGE_SEQ")
	@Column(name = "COOL_IOVRANGE_PK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangePk() {
		return coolIovrangePk;
	}

	public void setCoolIovrangePk(final BigDecimal coolIovrangePk) {
		this.coolIovrangePk = coolIovrangePk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COOL_IOVSUMMARY_FK", nullable = false)
	public CoolIovSummary getCoolIovSummary() {
		return coolIovSummary;
	}

	public void setCoolIovSummary(final CoolIovSummary coolIovSummary) {
		this.coolIovSummary = coolIovSummary;
	}

	@Column(name = "COOL_IOVRANGE_SINCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeSince() {
		return coolIovrangeSince;
	}

	public void setCoolIovrangeSince(final BigDecimal coolIovrangeSince) {
		this.coolIovrangeSince = coolIovrangeSince;
	}

	@Column(name = "COOL_IOVRANGE_UNTIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeUntil() {
		return coolIovrangeUntil;
	}

	public void setCoolIovrangeUntil(final BigDecimal coolIovrangeUntil) {
		this.coolIovrangeUntil = coolIovrangeUntil;
	}

	@Column(name = "COOL_IOVRANGE_NIOVS", precision = 22, scale = 0)
	public BigDecimal getCoolIovrangeNiovs() {
		return coolIovrangeNiovs;
	}

	public void setCoolIovrangeNiovs(final BigDecimal coolIovrangeNiovs) {
		this.coolIovrangeNiovs = coolIovrangeNiovs;
	}

	@Column(name = "COOL_IOVRANGE_ISHOLE")
	public Boolean getCoolIovrangeIshole() {
		return coolIovrangeIshole;
	}

	public void setCoolIovrangeIshole(final Boolean coolIovrangeIshole) {
		this.coolIovrangeIshole = coolIovrangeIshole;
	}

	@Column(name = "COOL_IOVBASE", length = 20)
	public String getCoolIovbase() {
		return coolIovbase;
	}

	public void setCoolIovbase(final String coolIovbase) {
		this.coolIovbase = coolIovbase;
	}

	@Column(name = "COOL_IOVSINCE_STR")
	public String getCoolIovsinceStr() {
		return coolIovsinceStr;
	}

	public void setCoolIovsinceStr(final String coolIovsinceStr) {
		this.coolIovsinceStr = coolIovsinceStr;
	}

	@Column(name = "COOL_IOVUNTIL_STR")
	public String getCoolIovuntilStr() {
		return coolIovuntilStr;
	}

	public void setCoolIovuntilStr(final String coolIovuntilStr) {
		this.coolIovuntilStr = coolIovuntilStr;
	}

	/**
	 * @return the runMin
	 */
	@Column(name = "COMA_RUN_MIN", precision = 12, scale = 0)
	public BigDecimal getComaRunMin() {
		return comaRunMin;
	}

	/**
	 * @param runMin
	 *            the runMin to set
	 */
	public void setComaRunMin(final BigDecimal runMin) {
		this.comaRunMin = runMin;
	}

	/**
	 * @return the runMax
	 */
	@Column(name = "COMA_RUN_MAX", precision = 12, scale = 0)
	public BigDecimal getComaRunMax() {
		return comaRunMax;
	}

	/**
	 * @param runMax
	 *            the runMax to set
	 */
	public void setComaRunMax(final BigDecimal runMax) {
		this.comaRunMax = runMax;
	}

	/**
	 * @return the comaRunStartTime
	 */
	@Column(name = "COMA_RUN_STARTTIME")
	public Date getComaRunStartTime() {
		return comaRunStartTime;
	}

	/**
	 * @param comaRunStartTime the comaRunStartTime to set
	 */
	public void setComaRunStartTime(final Date comaRunStartTime) {
		this.comaRunStartTime = comaRunStartTime;
	}

	/**
	 * @return the comaRunEndTime
	 */
	@Column(name = "COMA_RUN_ENDTIME")
	public Date getComaRunEndTime() {
		return comaRunEndTime;
	}

	/**
	 * @param comaRunEndTime the comaRunEndTime to set
	 */
	public void setComaRunEndTime(final Date comaRunEndTime) {
		this.comaRunEndTime = comaRunEndTime;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return super.hashCode();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		CoolIovRanges cobj = null;
		if (obj instanceof CoolIovRanges) {
			cobj = (CoolIovRanges) obj;
			if (cobj.getCoolIovrangeSince().equals(this.getCoolIovrangeSince())
					&& cobj.getCoolIovrangeUntil().equals(this.getCoolIovrangeUntil())
					&& cobj.getCoolIovrangeNiovs().equals(this.getCoolIovrangeNiovs())) {
				return true;
			}
		}
		return false;
	}

}
