package atlas.coma.model;

// Generated May 23, 2013 12:11:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CbViewPeriodsLumi generated by hbm2java
 */
@Entity
@Table(name = "CB_VIEW_PERIODS_LUMI", schema = "ATLAS_COND_TOOLS")
public class CbViewPeriodsLumi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8792073935055727030L;
	private CbViewPeriodsLumiId id;
	private BigDecimal deliveredLumi;

	public CbViewPeriodsLumi() {
	}

	public CbViewPeriodsLumi(CbViewPeriodsLumiId id, BigDecimal deliveredLumi) {
		this.id = id;
		this.deliveredLumi = deliveredLumi;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "PPeriod", column = @Column(name = "P_PERIOD", nullable = false, length = 32)),
			@AttributeOverride(name = "PProject", column = @Column(name = "P_PROJECT", nullable = false, length = 32)) })
	public CbViewPeriodsLumiId getId() {
		return this.id;
	}

	public void setId(CbViewPeriodsLumiId id) {
		this.id = id;
	}

	@Column(name = "DELIVERED_LUMI", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDeliveredLumi() {
		return this.deliveredLumi;
	}

	public void setDeliveredLumi(BigDecimal deliveredLumi) {
		this.deliveredLumi = deliveredLumi;
	}

}
