package atlas.coma.model;

// Generated May 23, 2013 12:11:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CbViewParentPeriodsLumiId generated by hbm2java
 */
@Embeddable
public class CbViewParentPeriodsLumiId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1569658498486200770L;
	private String PPeriod;
	private String PProject;

	public CbViewParentPeriodsLumiId() {
	}

	public CbViewParentPeriodsLumiId(String PPeriod, String PProject) {
		this.PPeriod = PPeriod;
		this.PProject = PProject;
	}

	@Column(name = "P_PERIOD", nullable = false, length = 32)
	public String getPPeriod() {
		return this.PPeriod;
	}

	public void setPPeriod(String PPeriod) {
		this.PPeriod = PPeriod;
	}

	@Column(name = "P_PROJECT", nullable = false, length = 32)
	public String getPProject() {
		return this.PProject;
	}

	public void setPProject(String PProject) {
		this.PProject = PProject;
	}

}
