package atlas.coma.model;

// Generated May 23, 2013 12:11:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CbViewParentPeriodsLumi generated by hbm2java
 */
@Entity
@Table(name = "CB_VIEW_PARENT_PERIODS_LUMI", schema = "ATLAS_COND_TOOLS")
public class CbViewParentPeriodsLumi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5968503776125965252L;
	private CbViewParentPeriodsLumiId id;
	private BigDecimal deliveredLumi;

	public CbViewParentPeriodsLumi() {
	}

	public CbViewParentPeriodsLumi(CbViewParentPeriodsLumiId id,
			BigDecimal deliveredLumi) {
		this.id = id;
		this.deliveredLumi = deliveredLumi;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "PPeriod", column = @Column(name = "P_PERIOD", nullable = false, length = 32)),
			@AttributeOverride(name = "PProject", column = @Column(name = "P_PROJECT", nullable = false, length = 32)) })
	public CbViewParentPeriodsLumiId getId() {
		return this.id;
	}

	public void setId(CbViewParentPeriodsLumiId id) {
		this.id = id;
	}

	@Column(name = "DELIVERED_LUMI", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDeliveredLumi() {
		return this.deliveredLumi;
	}

	public void setDeliveredLumi(BigDecimal deliveredLumi) {
		this.deliveredLumi = deliveredLumi;
	}

}
