package atlas.coma.model;

// Generated May 23, 2013 12:11:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CbViewSchemagtsId generated by hbm2java
 */
@Embeddable
public class CbViewSchemagtsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9138152718187701978L;

	private String gtagName;
	private String schemaName;
	private String dbName;

	public CbViewSchemagtsId() {
	}

	public CbViewSchemagtsId(String gtagName, String schemaName, String dbName) {
		this.gtagName = gtagName;
		this.schemaName = schemaName;
		this.dbName = dbName;
	}

	@Column(name = "GTAG_NAME", nullable = false)
	public String getGtagName() {
		return this.gtagName;
	}

	public void setGtagName(String gtagName) {
		this.gtagName = gtagName;
	}

	@Column(name = "SCHEMA_NAME", nullable = false, length = 32)
	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	@Column(name = "DB_NAME", nullable = false, length = 10)
	public String getDbName() {
		return this.dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

}
