package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComaCbInstances generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_INSTANCES"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbInstances  implements java.io.Serializable {


     private String cbiName;
     private String cbiDesc;
     private Set<ComaCbOwnerInstances> comaCbOwnerInstanceses = new HashSet<ComaCbOwnerInstances>(0);

    public ComaCbInstances() {
    }

	
    public ComaCbInstances(String cbiName) {
        this.cbiName = cbiName;
    }
    public ComaCbInstances(String cbiName, String cbiDesc, Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
       this.cbiName = cbiName;
       this.cbiDesc = cbiDesc;
       this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
    }
   
     @Id 

    
    @Column(name="CBI_NAME", nullable=false, length=10)
    public String getCbiName() {
        return this.cbiName;
    }
    
    public void setCbiName(String cbiName) {
        this.cbiName = cbiName;
    }

    
    @Column(name="CBI_DESC", length=4000)
    public String getCbiDesc() {
        return this.cbiDesc;
    }
    
    public void setCbiDesc(String cbiDesc) {
        this.cbiDesc = cbiDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbInstances")
    public Set<ComaCbOwnerInstances> getComaCbOwnerInstanceses() {
        return this.comaCbOwnerInstanceses;
    }
    
    public void setComaCbOwnerInstanceses(Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
        this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
    }




}


