package atlas.coma.model;

// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import atlas.cool.annotations.CoolQuery;

/**
 * ComaCbSchemas generated by hbm2java.
 */
@Entity
@Table(name = "COMA_CB_SCHEMAS", schema = "ATLAS_TAGS_METADATA")
@NamedQueries({
	@NamedQuery(name = ComaCbSchemas.QUERY_FINDSCHEMAS, query = "FROM ComaCbSchemas schemas "
			+ "WHERE ( "
			+ "cbsName like :sname) ")
})
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
public class ComaCbSchemas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5781479556211664530L;

	private String cbsName;
	private String cbsSystem;
	private String cbsDesc;
	private Set<ComaCbOwnerInstances> comaCbOwnerInstanceses = new HashSet<ComaCbOwnerInstances>(
			0);
	
	@CoolQuery(name = "coma.findschemas", params = "sname")
	public static final String QUERY_FINDSCHEMAS = "coma.findschemas";


	/**
	 * 
	 */
	public ComaCbSchemas() {
	}

	/**
	 * @param cbsName
	 */
	public ComaCbSchemas(final String cbsName) {
		this.cbsName = cbsName;
	}

	/**
	 * @param cbsName
	 * @param cbsSystem
	 * @param cbsDesc
	 * @param comaCbOwnerInstanceses
	 */
	public ComaCbSchemas(final String cbsName, final String cbsSystem,
			final String cbsDesc, final Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
		this.cbsName = cbsName;
		this.cbsSystem = cbsSystem;
		this.cbsDesc = cbsDesc;
		this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
	}

	/**
	 * @return
	 */
	@Id
	@Column(name = "CBS_NAME", nullable = false, length = 10)
	public String getCbsName() {
		return cbsName;
	}

	public void setCbsName(final String cbsName) {
		this.cbsName = cbsName;
	}

	/**
	 * @return
	 */
	@Column(name = "CBS_SYSTEM", length = 12)
	public String getCbsSystem() {
		return cbsSystem;
	}

	/**
	 * @param cbsSystem
	 */
	public void setCbsSystem(final String cbsSystem) {
		this.cbsSystem = cbsSystem;
	}

	/**
	 * @return
	 */
	@Column(name = "CBS_DESC", length = 4000)
	public String getCbsDesc() {
		return cbsDesc;
	}

	/**
	 * @param cbsDesc
	 */
	public void setCbsDesc(final String cbsDesc) {
		this.cbsDesc = cbsDesc;
	}

	/**
	 * @return
	 */
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "comaCbSchemas")
	public Set<ComaCbOwnerInstances> getComaCbOwnerInstanceses() {
		return comaCbOwnerInstanceses;
	}

	/**
	 * @param comaCbOwnerInstanceses
	 */
	public void setComaCbOwnerInstanceses(
			final Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
		this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
	}

}
