package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComaCbGtags generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_GTAGS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbGtags  implements java.io.Serializable {


     private BigDecimal cbgtIndex;
     private String tagName;
     private Boolean tagLockStatus;
     private String tagDescription;
     private String sysInstime;
     private Date cbgtInstime;
     private Boolean cbgtRank;
     private Boolean cbgtIntegrity;
     private Date comaInsDate;
     private Date comaUpdDate;
     private Set<ComaCbGtToOis> comaCbGtToOises = new HashSet<ComaCbGtToOis>(0);
     private Set<ComaCbGtToFts> comaCbGtToFtses = new HashSet<ComaCbGtToFts>(0);

    public ComaCbGtags() {
    }

	
    public ComaCbGtags(BigDecimal cbgtIndex) {
        this.cbgtIndex = cbgtIndex;
    }
    public ComaCbGtags(BigDecimal cbgtIndex, String tagName, Boolean tagLockStatus, String tagDescription, String sysInstime, Date cbgtInstime, Boolean cbgtRank, Boolean cbgtIntegrity, Date comaInsDate, Date comaUpdDate, Set<ComaCbGtToOis> comaCbGtToOises, Set<ComaCbGtToFts> comaCbGtToFtses) {
       this.cbgtIndex = cbgtIndex;
       this.tagName = tagName;
       this.tagLockStatus = tagLockStatus;
       this.tagDescription = tagDescription;
       this.sysInstime = sysInstime;
       this.cbgtInstime = cbgtInstime;
       this.cbgtRank = cbgtRank;
       this.cbgtIntegrity = cbgtIntegrity;
       this.comaInsDate = comaInsDate;
       this.comaUpdDate = comaUpdDate;
       this.comaCbGtToOises = comaCbGtToOises;
       this.comaCbGtToFtses = comaCbGtToFtses;
    }
   
     @Id 

    
    @Column(name="CBGT_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbgtIndex() {
        return this.cbgtIndex;
    }
    
    public void setCbgtIndex(BigDecimal cbgtIndex) {
        this.cbgtIndex = cbgtIndex;
    }

    
    @Column(name="TAG_NAME", unique=true)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    
    @Column(name="TAG_LOCK_STATUS", precision=1, scale=0)
    public Boolean getTagLockStatus() {
        return this.tagLockStatus;
    }
    
    public void setTagLockStatus(Boolean tagLockStatus) {
        this.tagLockStatus = tagLockStatus;
    }

    
    @Column(name="TAG_DESCRIPTION")
    public String getTagDescription() {
        return this.tagDescription;
    }
    
    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    
    @Column(name="SYS_INSTIME")
    public String getSysInstime() {
        return this.sysInstime;
    }
    
    public void setSysInstime(String sysInstime) {
        this.sysInstime = sysInstime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBGT_INSTIME", length=7)
    public Date getCbgtInstime() {
        return this.cbgtInstime;
    }
    
    public void setCbgtInstime(Date cbgtInstime) {
        this.cbgtInstime = cbgtInstime;
    }

    
    @Column(name="CBGT_RANK", precision=1, scale=0)
    public Boolean getCbgtRank() {
        return this.cbgtRank;
    }
    
    public void setCbgtRank(Boolean cbgtRank) {
        this.cbgtRank = cbgtRank;
    }

    
    @Column(name="CBGT_INTEGRITY", precision=1, scale=0)
    public Boolean getCbgtIntegrity() {
        return this.cbgtIntegrity;
    }
    
    public void setCbgtIntegrity(Boolean cbgtIntegrity) {
        this.cbgtIntegrity = cbgtIntegrity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_INS_DATE", length=7)
    public Date getComaInsDate() {
        return this.comaInsDate;
    }
    
    public void setComaInsDate(Date comaInsDate) {
        this.comaInsDate = comaInsDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_UPD_DATE", length=7)
    public Date getComaUpdDate() {
        return this.comaUpdDate;
    }
    
    public void setComaUpdDate(Date comaUpdDate) {
        this.comaUpdDate = comaUpdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbGtags")
    public Set<ComaCbGtToOis> getComaCbGtToOises() {
        return this.comaCbGtToOises;
    }
    
    public void setComaCbGtToOises(Set<ComaCbGtToOis> comaCbGtToOises) {
        this.comaCbGtToOises = comaCbGtToOises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbGtags")
    public Set<ComaCbGtToFts> getComaCbGtToFtses() {
        return this.comaCbGtToFtses;
    }
    
    public void setComaCbGtToFtses(Set<ComaCbGtToFts> comaCbGtToFtses) {
        this.comaCbGtToFtses = comaCbGtToFtses;
    }




}


