package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ComaCbReferences generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_REFERENCES"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbReferences  implements java.io.Serializable {


     private BigDecimal cbfIndex;
     private ComaCbNodes comaCbNodes;
     private String folderIovtablename;
     private String folderTagtablename;
     private String folderIov2tagtablename;
     private String folderChanneltablename;
     private String folderPayloadExtref;
     private Date comaInsDate;
     private Date comaUpdDate;

    public ComaCbReferences() {
    }

	
    public ComaCbReferences(ComaCbNodes comaCbNodes) {
        this.comaCbNodes = comaCbNodes;
    }
    public ComaCbReferences(ComaCbNodes comaCbNodes, String folderIovtablename, String folderTagtablename, String folderIov2tagtablename, String folderChanneltablename, String folderPayloadExtref, Date comaInsDate, Date comaUpdDate) {
       this.comaCbNodes = comaCbNodes;
       this.folderIovtablename = folderIovtablename;
       this.folderTagtablename = folderTagtablename;
       this.folderIov2tagtablename = folderIov2tagtablename;
       this.folderChanneltablename = folderChanneltablename;
       this.folderPayloadExtref = folderPayloadExtref;
       this.comaInsDate = comaInsDate;
       this.comaUpdDate = comaUpdDate;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="comaCbNodes"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="CBF_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbfIndex() {
        return this.cbfIndex;
    }
    
    public void setCbfIndex(BigDecimal cbfIndex) {
        this.cbfIndex = cbfIndex;
    }

@OneToOne(fetch=FetchType.LAZY)
    public ComaCbNodes getComaCbNodes() {
        return this.comaCbNodes;
    }
    
    public void setComaCbNodes(ComaCbNodes comaCbNodes) {
        this.comaCbNodes = comaCbNodes;
    }

    
    @Column(name="FOLDER_IOVTABLENAME")
    public String getFolderIovtablename() {
        return this.folderIovtablename;
    }
    
    public void setFolderIovtablename(String folderIovtablename) {
        this.folderIovtablename = folderIovtablename;
    }

    
    @Column(name="FOLDER_TAGTABLENAME")
    public String getFolderTagtablename() {
        return this.folderTagtablename;
    }
    
    public void setFolderTagtablename(String folderTagtablename) {
        this.folderTagtablename = folderTagtablename;
    }

    
    @Column(name="FOLDER_IOV2TAGTABLENAME")
    public String getFolderIov2tagtablename() {
        return this.folderIov2tagtablename;
    }
    
    public void setFolderIov2tagtablename(String folderIov2tagtablename) {
        this.folderIov2tagtablename = folderIov2tagtablename;
    }

    
    @Column(name="FOLDER_CHANNELTABLENAME")
    public String getFolderChanneltablename() {
        return this.folderChanneltablename;
    }
    
    public void setFolderChanneltablename(String folderChanneltablename) {
        this.folderChanneltablename = folderChanneltablename;
    }

    
    @Column(name="FOLDER_PAYLOAD_EXTREF")
    public String getFolderPayloadExtref() {
        return this.folderPayloadExtref;
    }
    
    public void setFolderPayloadExtref(String folderPayloadExtref) {
        this.folderPayloadExtref = folderPayloadExtref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_INS_DATE", length=7)
    public Date getComaInsDate() {
        return this.comaInsDate;
    }
    
    public void setComaInsDate(Date comaInsDate) {
        this.comaInsDate = comaInsDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_UPD_DATE", length=7)
    public Date getComaUpdDate() {
        return this.comaUpdDate;
    }
    
    public void setComaUpdDate(Date comaUpdDate) {
        this.comaUpdDate = comaUpdDate;
    }




}


