package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComaCbPcolumns generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_PCOLUMNS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbPcolumns  implements java.io.Serializable {


     private BigDecimal cbpIndex;
     private ComaCbNodes comaCbNodes;
     private String cbpColumn;
     private String cbpType;
     private String cbpDesc;
     private Date comaInsDate;
     private Date comaUpdDate;

    public ComaCbPcolumns() {
    }

	
    public ComaCbPcolumns(BigDecimal cbpIndex, ComaCbNodes comaCbNodes, String cbpColumn) {
        this.cbpIndex = cbpIndex;
        this.comaCbNodes = comaCbNodes;
        this.cbpColumn = cbpColumn;
    }
    public ComaCbPcolumns(BigDecimal cbpIndex, ComaCbNodes comaCbNodes, String cbpColumn, String cbpType, String cbpDesc, Date comaInsDate, Date comaUpdDate) {
       this.cbpIndex = cbpIndex;
       this.comaCbNodes = comaCbNodes;
       this.cbpColumn = cbpColumn;
       this.cbpType = cbpType;
       this.cbpDesc = cbpDesc;
       this.comaInsDate = comaInsDate;
       this.comaUpdDate = comaUpdDate;
    }
   
     @Id 

    
    @Column(name="CBP_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbpIndex() {
        return this.cbpIndex;
    }
    
    public void setCbpIndex(BigDecimal cbpIndex) {
        this.cbpIndex = cbpIndex;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBF_INDEX", nullable=false)
    public ComaCbNodes getComaCbNodes() {
        return this.comaCbNodes;
    }
    
    public void setComaCbNodes(ComaCbNodes comaCbNodes) {
        this.comaCbNodes = comaCbNodes;
    }

    
    @Column(name="CBP_COLUMN", nullable=false, length=32)
    public String getCbpColumn() {
        return this.cbpColumn;
    }
    
    public void setCbpColumn(String cbpColumn) {
        this.cbpColumn = cbpColumn;
    }

    
    @Column(name="CBP_TYPE", length=32)
    public String getCbpType() {
        return this.cbpType;
    }
    
    public void setCbpType(String cbpType) {
        this.cbpType = cbpType;
    }

    
    @Column(name="CBP_DESC", length=4000)
    public String getCbpDesc() {
        return this.cbpDesc;
    }
    
    public void setCbpDesc(String cbpDesc) {
        this.cbpDesc = cbpDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_INS_DATE", length=7)
    public Date getComaInsDate() {
        return this.comaInsDate;
    }
    
    public void setComaInsDate(Date comaInsDate) {
        this.comaInsDate = comaInsDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_UPD_DATE", length=7)
    public Date getComaUpdDate() {
        return this.comaUpdDate;
    }
    
    public void setComaUpdDate(Date comaUpdDate) {
        this.comaUpdDate = comaUpdDate;
    }




}


