package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComaCbSchemas generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_SCHEMAS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbSchemas  implements java.io.Serializable {


     private String cbsName;
     private String cbsSystem;
     private String cbsDesc;
     private Set<ComaCbOwnerInstances> comaCbOwnerInstanceses = new HashSet<ComaCbOwnerInstances>(0);

    public ComaCbSchemas() {
    }

	
    public ComaCbSchemas(String cbsName) {
        this.cbsName = cbsName;
    }
    public ComaCbSchemas(String cbsName, String cbsSystem, String cbsDesc, Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
       this.cbsName = cbsName;
       this.cbsSystem = cbsSystem;
       this.cbsDesc = cbsDesc;
       this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
    }
   
     @Id 

    
    @Column(name="CBS_NAME", nullable=false, length=10)
    public String getCbsName() {
        return this.cbsName;
    }
    
    public void setCbsName(String cbsName) {
        this.cbsName = cbsName;
    }

    
    @Column(name="CBS_SYSTEM", length=12)
    public String getCbsSystem() {
        return this.cbsSystem;
    }
    
    public void setCbsSystem(String cbsSystem) {
        this.cbsSystem = cbsSystem;
    }

    
    @Column(name="CBS_DESC", length=4000)
    public String getCbsDesc() {
        return this.cbsDesc;
    }
    
    public void setCbsDesc(String cbsDesc) {
        this.cbsDesc = cbsDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbSchemas")
    public Set<ComaCbOwnerInstances> getComaCbOwnerInstanceses() {
        return this.comaCbOwnerInstanceses;
    }
    
    public void setComaCbOwnerInstanceses(Set<ComaCbOwnerInstances> comaCbOwnerInstanceses) {
        this.comaCbOwnerInstanceses = comaCbOwnerInstanceses;
    }




}


