package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ComaCbamiGtagsTemp generated by hbm2java
 */
@Entity
@Table(name="COMA_CBAMI_GTAGS_TEMP"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbamiGtagsTemp  implements java.io.Serializable {


     private ComaCbamiGtagsTempId id;

    public ComaCbamiGtagsTemp() {
    }

    public ComaCbamiGtagsTemp(ComaCbamiGtagsTempId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tagName", column=@Column(name="TAG_NAME", nullable=false) ), 
        @AttributeOverride(name="isActive", column=@Column(name="IS_ACTIVE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="datasetCount", column=@Column(name="DATASET_COUNT", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="dateFirstDataset", column=@Column(name="DATE_FIRST_DATASET", nullable=false, length=7) ), 
        @AttributeOverride(name="dateLastDataset", column=@Column(name="DATE_LAST_DATASET", nullable=false, length=7) ) } )
    public ComaCbamiGtagsTempId getId() {
        return this.id;
    }
    
    public void setId(ComaCbamiGtagsTempId id) {
        this.id = id;
    }




}


