package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComaCbGtToFts generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_GT_TO_FTS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbGtToFts  implements java.io.Serializable {


     private BigDecimal cbg2fIndex;
     private ComaCbGtags comaCbGtags;
     private ComaCbFtags comaCbFtags;

    public ComaCbGtToFts() {
    }

    public ComaCbGtToFts(BigDecimal cbg2fIndex, ComaCbGtags comaCbGtags, ComaCbFtags comaCbFtags) {
       this.cbg2fIndex = cbg2fIndex;
       this.comaCbGtags = comaCbGtags;
       this.comaCbFtags = comaCbFtags;
    }
   
     @Id 

    
    @Column(name="CBG2F_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbg2fIndex() {
        return this.cbg2fIndex;
    }
    
    public void setCbg2fIndex(BigDecimal cbg2fIndex) {
        this.cbg2fIndex = cbg2fIndex;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBGT_INDEX", nullable=false)
    public ComaCbGtags getComaCbGtags() {
        return this.comaCbGtags;
    }
    
    public void setComaCbGtags(ComaCbGtags comaCbGtags) {
        this.comaCbGtags = comaCbGtags;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBFT_INDEX", nullable=false)
    public ComaCbFtags getComaCbFtags() {
        return this.comaCbFtags;
    }
    
    public void setComaCbFtags(ComaCbFtags comaCbFtags) {
        this.comaCbFtags = comaCbFtags;
    }




}


