package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComaCbgtsObs generated by hbm2java
 */
@Entity
@Table(name="COMA_CBGTS_OBS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbgtsObs  implements java.io.Serializable {


     private BigDecimal cbgtsoIndex;
     private BigDecimal cbgtsIndex;
     private String gtagState;
     private Date startTime;
     private String tagName;
     private Date endTime;
     private String cbgtsDesc;
     private String createUser;
     private Date createDate;
     private String modifyUser;
     private Date modifyDate;
     private String deleteUser;
     private Date deleteDate;

    public ComaCbgtsObs() {
    }

	
    public ComaCbgtsObs(BigDecimal cbgtsoIndex, BigDecimal cbgtsIndex, String gtagState, Date startTime, String tagName) {
        this.cbgtsoIndex = cbgtsoIndex;
        this.cbgtsIndex = cbgtsIndex;
        this.gtagState = gtagState;
        this.startTime = startTime;
        this.tagName = tagName;
    }
    public ComaCbgtsObs(BigDecimal cbgtsoIndex, BigDecimal cbgtsIndex, String gtagState, Date startTime, String tagName, Date endTime, String cbgtsDesc, String createUser, Date createDate, String modifyUser, Date modifyDate, String deleteUser, Date deleteDate) {
       this.cbgtsoIndex = cbgtsoIndex;
       this.cbgtsIndex = cbgtsIndex;
       this.gtagState = gtagState;
       this.startTime = startTime;
       this.tagName = tagName;
       this.endTime = endTime;
       this.cbgtsDesc = cbgtsDesc;
       this.createUser = createUser;
       this.createDate = createDate;
       this.modifyUser = modifyUser;
       this.modifyDate = modifyDate;
       this.deleteUser = deleteUser;
       this.deleteDate = deleteDate;
    }
   
     @Id 

    
    @Column(name="CBGTSO_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbgtsoIndex() {
        return this.cbgtsoIndex;
    }
    
    public void setCbgtsoIndex(BigDecimal cbgtsoIndex) {
        this.cbgtsoIndex = cbgtsoIndex;
    }

    
    @Column(name="CBGTS_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbgtsIndex() {
        return this.cbgtsIndex;
    }
    
    public void setCbgtsIndex(BigDecimal cbgtsIndex) {
        this.cbgtsIndex = cbgtsIndex;
    }

    
    @Column(name="GTAG_STATE", nullable=false, length=10)
    public String getGtagState() {
        return this.gtagState;
    }
    
    public void setGtagState(String gtagState) {
        this.gtagState = gtagState;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_TIME", nullable=false, length=7)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="TAG_NAME", nullable=false)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_TIME", length=7)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="CBGTS_DESC", length=4000)
    public String getCbgtsDesc() {
        return this.cbgtsDesc;
    }
    
    public void setCbgtsDesc(String cbgtsDesc) {
        this.cbgtsDesc = cbgtsDesc;
    }

    
    @Column(name="CREATE_USER", length=32)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="MODIFY_USER", length=32)
    public String getModifyUser() {
        return this.modifyUser;
    }
    
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFY_DATE", length=7)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    
    @Column(name="DELETE_USER", length=32)
    public String getDeleteUser() {
        return this.deleteUser;
    }
    
    public void setDeleteUser(String deleteUser) {
        this.deleteUser = deleteUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DELETE_DATE", length=7)
    public Date getDeleteDate() {
        return this.deleteDate;
    }
    
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }




}


