package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComaCbNodes generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_NODES"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbNodes  implements java.io.Serializable {


     private BigDecimal cbfIndex;
     private ComaCbOwnerInstances comaCbOwnerInstances;
     private String nodeFullpath;
     private String nodeName;
     private Long nodeId;
     private Long nodeParentid;
     private Boolean nodeIsleaf;
     private String nodeInstime;
     private String lastmodDate;
     private Date cbfLastmodDate;
     private String nodeDescription;
     private Long folderVersioning;
     private String cbfNodePath;
     private String cbfIovBase;
     private String cbfAttType;
     private BigDecimal cbfChanCount;
     private BigDecimal cbfPayloadCount;
     private Date comaInsDate;
     private Date comaUpdDate;
     private ComaCbReferences comaCbReferences;
     private Set<ComaCbPcolumns> comaCbPcolumnses = new HashSet<ComaCbPcolumns>(0);
     private Set<ComaCbFtags> comaCbFtagses = new HashSet<ComaCbFtags>(0);

    public ComaCbNodes() {
    }

	
    public ComaCbNodes(BigDecimal cbfIndex, ComaCbOwnerInstances comaCbOwnerInstances, String nodeFullpath) {
        this.cbfIndex = cbfIndex;
        this.comaCbOwnerInstances = comaCbOwnerInstances;
        this.nodeFullpath = nodeFullpath;
    }
    public ComaCbNodes(BigDecimal cbfIndex, ComaCbOwnerInstances comaCbOwnerInstances, String nodeFullpath, String nodeName, Long nodeId, Long nodeParentid, Boolean nodeIsleaf, String nodeInstime, String lastmodDate, Date cbfLastmodDate, String nodeDescription, Long folderVersioning, String cbfNodePath, String cbfIovBase, String cbfAttType, BigDecimal cbfChanCount, BigDecimal cbfPayloadCount, Date comaInsDate, Date comaUpdDate, ComaCbReferences comaCbReferences, Set<ComaCbPcolumns> comaCbPcolumnses, Set<ComaCbFtags> comaCbFtagses) {
       this.cbfIndex = cbfIndex;
       this.comaCbOwnerInstances = comaCbOwnerInstances;
       this.nodeFullpath = nodeFullpath;
       this.nodeName = nodeName;
       this.nodeId = nodeId;
       this.nodeParentid = nodeParentid;
       this.nodeIsleaf = nodeIsleaf;
       this.nodeInstime = nodeInstime;
       this.lastmodDate = lastmodDate;
       this.cbfLastmodDate = cbfLastmodDate;
       this.nodeDescription = nodeDescription;
       this.folderVersioning = folderVersioning;
       this.cbfNodePath = cbfNodePath;
       this.cbfIovBase = cbfIovBase;
       this.cbfAttType = cbfAttType;
       this.cbfChanCount = cbfChanCount;
       this.cbfPayloadCount = cbfPayloadCount;
       this.comaInsDate = comaInsDate;
       this.comaUpdDate = comaUpdDate;
       this.comaCbReferences = comaCbReferences;
       this.comaCbPcolumnses = comaCbPcolumnses;
       this.comaCbFtagses = comaCbFtagses;
    }
   
     @Id 

    
    @Column(name="CBF_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbfIndex() {
        return this.cbfIndex;
    }
    
    public void setCbfIndex(BigDecimal cbfIndex) {
        this.cbfIndex = cbfIndex;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBOI_INDEX", nullable=false)
    public ComaCbOwnerInstances getComaCbOwnerInstances() {
        return this.comaCbOwnerInstances;
    }
    
    public void setComaCbOwnerInstances(ComaCbOwnerInstances comaCbOwnerInstances) {
        this.comaCbOwnerInstances = comaCbOwnerInstances;
    }

    
    @Column(name="NODE_FULLPATH", nullable=false)
    public String getNodeFullpath() {
        return this.nodeFullpath;
    }
    
    public void setNodeFullpath(String nodeFullpath) {
        this.nodeFullpath = nodeFullpath;
    }

    
    @Column(name="NODE_NAME")
    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    
    @Column(name="NODE_ID", precision=10, scale=0)
    public Long getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    
    @Column(name="NODE_PARENTID", precision=10, scale=0)
    public Long getNodeParentid() {
        return this.nodeParentid;
    }
    
    public void setNodeParentid(Long nodeParentid) {
        this.nodeParentid = nodeParentid;
    }

    
    @Column(name="NODE_ISLEAF", precision=1, scale=0)
    public Boolean getNodeIsleaf() {
        return this.nodeIsleaf;
    }
    
    public void setNodeIsleaf(Boolean nodeIsleaf) {
        this.nodeIsleaf = nodeIsleaf;
    }

    
    @Column(name="NODE_INSTIME")
    public String getNodeInstime() {
        return this.nodeInstime;
    }
    
    public void setNodeInstime(String nodeInstime) {
        this.nodeInstime = nodeInstime;
    }

    
    @Column(name="LASTMOD_DATE")
    public String getLastmodDate() {
        return this.lastmodDate;
    }
    
    public void setLastmodDate(String lastmodDate) {
        this.lastmodDate = lastmodDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBF_LASTMOD_DATE", length=7)
    public Date getCbfLastmodDate() {
        return this.cbfLastmodDate;
    }
    
    public void setCbfLastmodDate(Date cbfLastmodDate) {
        this.cbfLastmodDate = cbfLastmodDate;
    }

    
    @Column(name="NODE_DESCRIPTION")
    public String getNodeDescription() {
        return this.nodeDescription;
    }
    
    public void setNodeDescription(String nodeDescription) {
        this.nodeDescription = nodeDescription;
    }

    
    @Column(name="FOLDER_VERSIONING", precision=10, scale=0)
    public Long getFolderVersioning() {
        return this.folderVersioning;
    }
    
    public void setFolderVersioning(Long folderVersioning) {
        this.folderVersioning = folderVersioning;
    }

    
    @Column(name="CBF_NODE_PATH")
    public String getCbfNodePath() {
        return this.cbfNodePath;
    }
    
    public void setCbfNodePath(String cbfNodePath) {
        this.cbfNodePath = cbfNodePath;
    }

    
    @Column(name="CBF_IOV_BASE", length=10)
    public String getCbfIovBase() {
        return this.cbfIovBase;
    }
    
    public void setCbfIovBase(String cbfIovBase) {
        this.cbfIovBase = cbfIovBase;
    }

    
    @Column(name="CBF_ATT_TYPE", length=50)
    public String getCbfAttType() {
        return this.cbfAttType;
    }
    
    public void setCbfAttType(String cbfAttType) {
        this.cbfAttType = cbfAttType;
    }

    
    @Column(name="CBF_CHAN_COUNT", precision=38, scale=0)
    public BigDecimal getCbfChanCount() {
        return this.cbfChanCount;
    }
    
    public void setCbfChanCount(BigDecimal cbfChanCount) {
        this.cbfChanCount = cbfChanCount;
    }

    
    @Column(name="CBF_PAYLOAD_COUNT", precision=38, scale=0)
    public BigDecimal getCbfPayloadCount() {
        return this.cbfPayloadCount;
    }
    
    public void setCbfPayloadCount(BigDecimal cbfPayloadCount) {
        this.cbfPayloadCount = cbfPayloadCount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_INS_DATE", length=7)
    public Date getComaInsDate() {
        return this.comaInsDate;
    }
    
    public void setComaInsDate(Date comaInsDate) {
        this.comaInsDate = comaInsDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_UPD_DATE", length=7)
    public Date getComaUpdDate() {
        return this.comaUpdDate;
    }
    
    public void setComaUpdDate(Date comaUpdDate) {
        this.comaUpdDate = comaUpdDate;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="comaCbNodes")
    public ComaCbReferences getComaCbReferences() {
        return this.comaCbReferences;
    }
    
    public void setComaCbReferences(ComaCbReferences comaCbReferences) {
        this.comaCbReferences = comaCbReferences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbNodes")
    public Set<ComaCbPcolumns> getComaCbPcolumnses() {
        return this.comaCbPcolumnses;
    }
    
    public void setComaCbPcolumnses(Set<ComaCbPcolumns> comaCbPcolumnses) {
        this.comaCbPcolumnses = comaCbPcolumnses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbNodes")
    public Set<ComaCbFtags> getComaCbFtagses() {
        return this.comaCbFtagses;
    }
    
    public void setComaCbFtagses(Set<ComaCbFtags> comaCbFtagses) {
        this.comaCbFtagses = comaCbFtagses;
    }




}


