package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComaCbGtToOis generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_GT_TO_OIS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbGtToOis  implements java.io.Serializable {


     private BigDecimal cbg2oIndex;
     private ComaCbGtags comaCbGtags;
     private ComaCbOwnerInstances comaCbOwnerInstances;
     private Boolean tagLockStatus;
     private String tagDescription;
     private String sysInstime;

    public ComaCbGtToOis() {
    }

	
    public ComaCbGtToOis(BigDecimal cbg2oIndex, ComaCbGtags comaCbGtags, ComaCbOwnerInstances comaCbOwnerInstances) {
        this.cbg2oIndex = cbg2oIndex;
        this.comaCbGtags = comaCbGtags;
        this.comaCbOwnerInstances = comaCbOwnerInstances;
    }
    public ComaCbGtToOis(BigDecimal cbg2oIndex, ComaCbGtags comaCbGtags, ComaCbOwnerInstances comaCbOwnerInstances, Boolean tagLockStatus, String tagDescription, String sysInstime) {
       this.cbg2oIndex = cbg2oIndex;
       this.comaCbGtags = comaCbGtags;
       this.comaCbOwnerInstances = comaCbOwnerInstances;
       this.tagLockStatus = tagLockStatus;
       this.tagDescription = tagDescription;
       this.sysInstime = sysInstime;
    }
   
     @Id 

    
    @Column(name="CBG2O_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbg2oIndex() {
        return this.cbg2oIndex;
    }
    
    public void setCbg2oIndex(BigDecimal cbg2oIndex) {
        this.cbg2oIndex = cbg2oIndex;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBGT_INDEX", nullable=false)
    public ComaCbGtags getComaCbGtags() {
        return this.comaCbGtags;
    }
    
    public void setComaCbGtags(ComaCbGtags comaCbGtags) {
        this.comaCbGtags = comaCbGtags;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBOI_INDEX", nullable=false)
    public ComaCbOwnerInstances getComaCbOwnerInstances() {
        return this.comaCbOwnerInstances;
    }
    
    public void setComaCbOwnerInstances(ComaCbOwnerInstances comaCbOwnerInstances) {
        this.comaCbOwnerInstances = comaCbOwnerInstances;
    }

    
    @Column(name="TAG_LOCK_STATUS", precision=1, scale=0)
    public Boolean getTagLockStatus() {
        return this.tagLockStatus;
    }
    
    public void setTagLockStatus(Boolean tagLockStatus) {
        this.tagLockStatus = tagLockStatus;
    }

    
    @Column(name="TAG_DESCRIPTION")
    public String getTagDescription() {
        return this.tagDescription;
    }
    
    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    
    @Column(name="SYS_INSTIME")
    public String getSysInstime() {
        return this.sysInstime;
    }
    
    public void setSysInstime(String sysInstime) {
        this.sysInstime = sysInstime;
    }




}


