package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComaCbFtags generated by hbm2java
 */
@Entity
@Table(name="COMA_CB_FTAGS"
    ,schema="ATLAS_TAGS_METADATA"
)
public class ComaCbFtags  implements java.io.Serializable {


     private BigDecimal cbftIndex;
     private ComaCbNodes comaCbNodes;
     private String tagName;
     private Boolean tagLockStatus;
     private String tagDescription;
     private String sysInstime;
     private Date cbftInstime;
     private Long cbftNodeId;
     private BigDecimal cbftRowcount;
     private Date cbftLastObjtime;
     private Date cbftSinceTime;
     private Date cbftUntilTime;
     private Date comaInsDate;
     private Date comaUpdDate;
     private Set<ComaCbGtToFts> comaCbGtToFtses = new HashSet<ComaCbGtToFts>(0);

    public ComaCbFtags() {
    }

	
    public ComaCbFtags(BigDecimal cbftIndex, ComaCbNodes comaCbNodes, String tagName) {
        this.cbftIndex = cbftIndex;
        this.comaCbNodes = comaCbNodes;
        this.tagName = tagName;
    }
    public ComaCbFtags(BigDecimal cbftIndex, ComaCbNodes comaCbNodes, String tagName, Boolean tagLockStatus, String tagDescription, String sysInstime, Date cbftInstime, Long cbftNodeId, BigDecimal cbftRowcount, Date cbftLastObjtime, Date cbftSinceTime, Date cbftUntilTime, Date comaInsDate, Date comaUpdDate, Set<ComaCbGtToFts> comaCbGtToFtses) {
       this.cbftIndex = cbftIndex;
       this.comaCbNodes = comaCbNodes;
       this.tagName = tagName;
       this.tagLockStatus = tagLockStatus;
       this.tagDescription = tagDescription;
       this.sysInstime = sysInstime;
       this.cbftInstime = cbftInstime;
       this.cbftNodeId = cbftNodeId;
       this.cbftRowcount = cbftRowcount;
       this.cbftLastObjtime = cbftLastObjtime;
       this.cbftSinceTime = cbftSinceTime;
       this.cbftUntilTime = cbftUntilTime;
       this.comaInsDate = comaInsDate;
       this.comaUpdDate = comaUpdDate;
       this.comaCbGtToFtses = comaCbGtToFtses;
    }
   
     @Id 

    
    @Column(name="CBFT_INDEX", nullable=false, precision=38, scale=0)
    public BigDecimal getCbftIndex() {
        return this.cbftIndex;
    }
    
    public void setCbftIndex(BigDecimal cbftIndex) {
        this.cbftIndex = cbftIndex;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CBF_INDEX", nullable=false)
    public ComaCbNodes getComaCbNodes() {
        return this.comaCbNodes;
    }
    
    public void setComaCbNodes(ComaCbNodes comaCbNodes) {
        this.comaCbNodes = comaCbNodes;
    }

    
    @Column(name="TAG_NAME", nullable=false)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    
    @Column(name="TAG_LOCK_STATUS", precision=1, scale=0)
    public Boolean getTagLockStatus() {
        return this.tagLockStatus;
    }
    
    public void setTagLockStatus(Boolean tagLockStatus) {
        this.tagLockStatus = tagLockStatus;
    }

    
    @Column(name="TAG_DESCRIPTION")
    public String getTagDescription() {
        return this.tagDescription;
    }
    
    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    
    @Column(name="SYS_INSTIME")
    public String getSysInstime() {
        return this.sysInstime;
    }
    
    public void setSysInstime(String sysInstime) {
        this.sysInstime = sysInstime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBFT_INSTIME", length=7)
    public Date getCbftInstime() {
        return this.cbftInstime;
    }
    
    public void setCbftInstime(Date cbftInstime) {
        this.cbftInstime = cbftInstime;
    }

    
    @Column(name="CBFT_NODE_ID", precision=10, scale=0)
    public Long getCbftNodeId() {
        return this.cbftNodeId;
    }
    
    public void setCbftNodeId(Long cbftNodeId) {
        this.cbftNodeId = cbftNodeId;
    }

    
    @Column(name="CBFT_ROWCOUNT", precision=38, scale=0)
    public BigDecimal getCbftRowcount() {
        return this.cbftRowcount;
    }
    
    public void setCbftRowcount(BigDecimal cbftRowcount) {
        this.cbftRowcount = cbftRowcount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBFT_LAST_OBJTIME", length=7)
    public Date getCbftLastObjtime() {
        return this.cbftLastObjtime;
    }
    
    public void setCbftLastObjtime(Date cbftLastObjtime) {
        this.cbftLastObjtime = cbftLastObjtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBFT_SINCE_TIME", length=7)
    public Date getCbftSinceTime() {
        return this.cbftSinceTime;
    }
    
    public void setCbftSinceTime(Date cbftSinceTime) {
        this.cbftSinceTime = cbftSinceTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CBFT_UNTIL_TIME", length=7)
    public Date getCbftUntilTime() {
        return this.cbftUntilTime;
    }
    
    public void setCbftUntilTime(Date cbftUntilTime) {
        this.cbftUntilTime = cbftUntilTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_INS_DATE", length=7)
    public Date getComaInsDate() {
        return this.comaInsDate;
    }
    
    public void setComaInsDate(Date comaInsDate) {
        this.comaInsDate = comaInsDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMA_UPD_DATE", length=7)
    public Date getComaUpdDate() {
        return this.comaUpdDate;
    }
    
    public void setComaUpdDate(Date comaUpdDate) {
        this.comaUpdDate = comaUpdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comaCbFtags")
    public Set<ComaCbGtToFts> getComaCbGtToFtses() {
        return this.comaCbGtToFtses;
    }
    
    public void setComaCbGtToFtses(Set<ComaCbGtToFts> comaCbGtToFtses) {
        this.comaCbGtToFtses = comaCbGtToFtses;
    }




}


