package atlas.coma.model;
// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComaCbamiGtagsTempId generated by hbm2java
 */
@Embeddable
public class ComaCbamiGtagsTempId  implements java.io.Serializable {


     private String tagName;
     private Boolean isActive;
     private BigDecimal datasetCount;
     private Date dateFirstDataset;
     private Date dateLastDataset;

    public ComaCbamiGtagsTempId() {
    }

    public ComaCbamiGtagsTempId(String tagName, Boolean isActive, BigDecimal datasetCount, Date dateFirstDataset, Date dateLastDataset) {
       this.tagName = tagName;
       this.isActive = isActive;
       this.datasetCount = datasetCount;
       this.dateFirstDataset = dateFirstDataset;
       this.dateLastDataset = dateLastDataset;
    }
   


    @Column(name="TAG_NAME", nullable=false)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }


    @Column(name="IS_ACTIVE", nullable=false, precision=1, scale=0)
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }


    @Column(name="DATASET_COUNT", nullable=false, precision=38, scale=0)
    public BigDecimal getDatasetCount() {
        return this.datasetCount;
    }
    
    public void setDatasetCount(BigDecimal datasetCount) {
        this.datasetCount = datasetCount;
    }


    @Column(name="DATE_FIRST_DATASET", nullable=false, length=7)
    public Date getDateFirstDataset() {
        return this.dateFirstDataset;
    }
    
    public void setDateFirstDataset(Date dateFirstDataset) {
        this.dateFirstDataset = dateFirstDataset;
    }


    @Column(name="DATE_LAST_DATASET", nullable=false, length=7)
    public Date getDateLastDataset() {
        return this.dateLastDataset;
    }
    
    public void setDateLastDataset(Date dateLastDataset) {
        this.dateLastDataset = dateLastDataset;
    }




}


