package atlas.coma.model;

// Generated Apr 22, 2013 12:14:54 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import atlas.cool.annotations.CoolQuery;

/**
 * ComaCbGtagStates generated by hbm2java.
 */
@Entity
@Table(name = "COMA_CB_GTAG_STATES", schema = "ATLAS_TAGS_METADATA")
@NamedQueries({
		@NamedQuery(name = ComaCbGtagStates.QUERY_FINDSTATE, query = "FROM ComaCbGtagStates states "
				+ "WHERE ( " + "gtagState like :state) order by start_time desc"),
		@NamedQuery(name = ComaCbGtagStates.QUERY_FINDSTATEATTIME, query = "FROM ComaCbGtagStates states "
				+ " WHERE "
				+ " gtagState like :state AND ("
				+ " :time > startTime AND ( :time <= endTime OR endTime is null)) "
				+ " order by start_time desc") })
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
public class ComaCbGtagStates implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6464004495348605095L;

	private BigDecimal cbgtsIndex;
	private String gtagState;
	private String tagName;
	private Date startTime;
	private Date endTime;
	private String cbgtsDesc;
	private String createUser;
	private Date createDate;
	private String modifyUser;
	private Date modifyDate;

	@CoolQuery(name = "coma.findgtaginstate", params = "state")
	public static final String QUERY_FINDSTATE = "coma.findgtaginstate";
	@CoolQuery(name = "coma.findgtagattime", params = "state;time")
	public static final String QUERY_FINDSTATEATTIME = "coma.findgtagattime";

	/**
	 * 
	 */
	public ComaCbGtagStates() {
	}

	/**
	 * @param cbgtsIndex
	 * @param gtagState
	 * @param tagName
	 * @param startTime
	 */
	public ComaCbGtagStates(final BigDecimal cbgtsIndex, final String gtagState,
			final String tagName, final Date startTime) {
		this.cbgtsIndex = cbgtsIndex;
		this.gtagState = gtagState;
		this.tagName = tagName;
		this.startTime = startTime;
	}

	/**
	 * @param cbgtsIndex
	 * @param gtagState
	 * @param tagName
	 * @param startTime
	 * @param endTime
	 * @param cbgtsDesc
	 * @param createUser
	 * @param createDate
	 * @param modifyUser
	 * @param modifyDate
	 */
	public ComaCbGtagStates(final BigDecimal cbgtsIndex, final String gtagState,
			final String tagName, final Date startTime, final Date endTime,
			final String cbgtsDesc, final String createUser, final Date createDate,
			final String modifyUser, final Date modifyDate) {
		this.cbgtsIndex = cbgtsIndex;
		this.gtagState = gtagState;
		this.tagName = tagName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.cbgtsDesc = cbgtsDesc;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modifyUser = modifyUser;
		this.modifyDate = modifyDate;
	}

	@Id
	@Column(name = "CBGTS_INDEX", nullable = false, precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getCbgtsIndex() {
		return cbgtsIndex;
	}

	/**
	 * @param cbgtsIndex
	 */
	public void setCbgtsIndex(final BigDecimal cbgtsIndex) {
		this.cbgtsIndex = cbgtsIndex;
	}

	/**
	 * @return
	 */
	@Column(name = "GTAG_STATE", nullable = false, length = 10)
	@XmlElement
	public String getGtagState() {
		return gtagState;
	}

	/**
	 * @param gtagState
	 */
	public void setGtagState(final String gtagState) {
		this.gtagState = gtagState;
	}

	/**
	 * @return
	 */
	@Column(name = "TAG_NAME", nullable = false)
	@XmlElement
	public String getTagName() {
		return tagName;
	}

	/**
	 * @param tagName
	 */
	public void setTagName(final String tagName) {
		this.tagName = tagName;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "START_TIME", nullable = false, length = 7)
	@XmlElement
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * @param startTime
	 */
	public void setStartTime(final Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "END_TIME", length = 7)
	@XmlElement
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime
	 */
	public void setEndTime(final Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return
	 */
	@Column(name = "CBGTS_DESC", length = 4000)
	@XmlElement
	public String getCbgtsDesc() {
		return cbgtsDesc;
	}

	/**
	 * @param cbgtsDesc
	 */
	public void setCbgtsDesc(final String cbgtsDesc) {
		this.cbgtsDesc = cbgtsDesc;
	}

	/**
	 * @return
	 */
	@Column(name = "CREATE_USER", length = 32)
	@XmlElement
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser
	 */
	public void setCreateUser(final String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	@XmlElement
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * @param createDate
	 */
	public void setCreateDate(final Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * @return
	 */
	@Column(name = "MODIFY_USER", length = 32)
	@XmlElement
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * @param modifyUser
	 */
	public void setModifyUser(final String modifyUser) {
		this.modifyUser = modifyUser;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_DATE", length = 7)
	@XmlElement
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * @param modifyDate
	 */
	public void setModifyDate(final Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
