package atlas.coma.model;

// Generated May 23, 2013 12:11:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import atlas.cool.annotations.CoolQuery;

/**
 * CrViewRuninfo generated by hbm2java.
 */
@Entity
@Table(name = "CR_VIEW_RUNINFO", schema = "ATLAS_COND_TOOLS")
@NamedQueries({
		@NamedQuery(name = CrViewRuninfo.QUERY_FINDRUNS, query = "FROM CrViewRuninfo runs "
				+ "WHERE ( "
				+ "runNumber >= :start AND runNumber < :end) "
				+ "ORDER BY runNumber ASC"),
		@NamedQuery(name = CrViewRuninfo.QUERY_FINDRUNS_TYPEPROJ, query = "FROM CrViewRuninfo runs "
				+ "WHERE ( "
				+ "runNumber >= :start AND runNumber < :end) AND "
				+ " ((runType like :rtype) AND (PProject like :pproj)) "
				+ "ORDER BY runNumber ASC"),
		@NamedQuery(name = CrViewRuninfo.QUERY_FINDRUNS_BYTIME, query = "FROM  CrViewRuninfo runs  "
				+ "WHERE (startTime >= :since AND startTime < :until) OR (endTime >= :since AND endTime < :until) "
				+ " OR (:since >= startTime AND :since < endTime) "
				+ "ORDER BY runNumber ASC"),
		@NamedQuery(name = CrViewRuninfo.QUERY_FINDRUNS_BYTIME_TYPEPROJ, query = "FROM  CrViewRuninfo runs  "
				+ "WHERE ((startTime >= :since AND startTime < :until) OR (endTime >= :since AND endTime < :until) "
				+ " OR (:since >= startTime AND :since < endTime)) AND "
				+ " ((runType like :rtype) AND (PProject like :pproj)) "
				+ "ORDER BY runNumber ASC")

})
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
public class CrViewRuninfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4705460690382536688L;
	private BigDecimal runNumber;
	private Timestamp startTime;
	private Timestamp endTime;
	private String dataSource;
	private String runType;
	private String runTypeDesc;
	private String PProject;
	private String PDesc;
	private BigDecimal integLumi;
	private BigDecimal startLbn;
	private BigDecimal endLbn;
	private String PPeriod;
	private BigDecimal l1Events;
	private BigDecimal l2Events;
	private BigDecimal efEvents;
	private BigDecimal recordedEvents;
	private String partitionName;

	@CoolQuery(name = "coma.findrunsinrange", params = "start;end")
	public static final String QUERY_FINDRUNS = "coma.findrunsinrange";
	@CoolQuery(name = "coma.findrunsintimerange", params = "since;until")
	public static final String QUERY_FINDRUNS_BYTIME = "coma.findrunsintimerange";
	@CoolQuery(name = "coma.findrunsinrangetypeproj", params = "start;end;rtype;pproj")
	public static final String QUERY_FINDRUNS_TYPEPROJ = "coma.findrunsinrangetypeproj";
	@CoolQuery(name = "coma.findrunsintimerangetypeproj", params = "since;until;rtype;pproj")
	public static final String QUERY_FINDRUNS_BYTIME_TYPEPROJ = "coma.findrunsintimerangetypeproj";

	/**
	 * Empty ctor.
	 */
	public CrViewRuninfo() {
	}

	/**
	 * @param runNumber
	 * @param startTime
	 * @param endTime
	 * @param dataSource
	 * @param runType
	 * @param runTypeDesc
	 * @param PProject
	 * @param PDesc
	 * @param integLumi
	 * @param startLbn
	 * @param endLbn
	 * @param PPeriod
	 * @param l1Events
	 * @param l2Events
	 * @param efEvents
	 * @param recordedEvents
	 * @param partitionName
	 */
	public CrViewRuninfo(final BigDecimal runNumber, final Timestamp startTime,
			final Timestamp endTime, final String dataSource, final String runType,
			final String runTypeDesc, final String PProject, final String PDesc,
			final BigDecimal integLumi, final BigDecimal startLbn,
			final BigDecimal endLbn, final String PPeriod, final BigDecimal l1Events,
			final BigDecimal l2Events, final BigDecimal efEvents,
			final BigDecimal recordedEvents, final String partitionName) {
		this.runNumber = runNumber;
		this.startTime = startTime;
		this.endTime = endTime;
		this.dataSource = dataSource;
		this.runType = runType;
		this.runTypeDesc = runTypeDesc;
		this.PProject = PProject;
		this.PDesc = PDesc;
		this.integLumi = integLumi;
		this.startLbn = startLbn;
		this.endLbn = endLbn;
		this.PPeriod = PPeriod;
		this.l1Events = l1Events;
		this.l2Events = l2Events;
		this.efEvents = efEvents;
		this.recordedEvents = recordedEvents;
		this.partitionName = partitionName;
	}

	@Id
	@Column(name = "RUN_NUMBER", nullable = false, precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getRunNumber() {
		return runNumber;
	}

	public void setRunNumber(final BigDecimal runNumber) {
		this.runNumber = runNumber;
	}

	@Column(name = "START_TIME", nullable = false)
	@XmlElement
	@XmlJavaTypeAdapter(atlas.rest.jaxb.adapters.TimestampXmlAdapter.class)
	public Timestamp getStartTime() {
		return startTime;
	}

	public void setStartTime(final Timestamp startTime) {
		this.startTime = startTime;
	}

	@Column(name = "END_TIME", nullable = false)
	@XmlElement
	@XmlJavaTypeAdapter(atlas.rest.jaxb.adapters.TimestampXmlAdapter.class)
	public Timestamp getEndTime() {
		return endTime;
	}

	public void setEndTime(final Timestamp endTime) {
		this.endTime = endTime;
	}

	@Column(name = "DATA_SOURCE", nullable = false)
	@XmlElement
	public String getDataSource() {
		return dataSource;
	}

	public void setDataSource(final String dataSource) {
		this.dataSource = dataSource;
	}

	@Column(name = "RUN_TYPE", nullable = false)
	@XmlElement
	public String getRunType() {
		return runType;
	}

	public void setRunType(final String runType) {
		this.runType = runType;
	}

	@Column(name = "RUN_TYPE_DESC", length = 4000)
	@XmlElement
	public String getRunTypeDesc() {
		return runTypeDesc;
	}

	public void setRunTypeDesc(final String runTypeDesc) {
		this.runTypeDesc = runTypeDesc;
	}

	@Column(name = "P_PROJECT", length = 32)
	@XmlElement
	public String getPProject() {
		return PProject;
	}

	public void setPProject(final String PProject) {
		this.PProject = PProject;
	}

	@Column(name = "P_DESC", length = 4000)
	@XmlElement
	public String getPDesc() {
		return PDesc;
	}

	public void setPDesc(final String PDesc) {
		this.PDesc = PDesc;
	}

	@Column(name = "INTEG_LUMI", nullable = false, precision = 22, scale = 0)
	@XmlElement
	public BigDecimal getIntegLumi() {
		return integLumi;
	}

	public void setIntegLumi(final BigDecimal integLumi) {
		this.integLumi = integLumi;
	}

	@Column(name = "START_LBN", nullable = false, precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getStartLbn() {
		return startLbn;
	}

	public void setStartLbn(final BigDecimal startLbn) {
		this.startLbn = startLbn;
	}

	@Column(name = "END_LBN", nullable = false, precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getEndLbn() {
		return endLbn;
	}

	public void setEndLbn(final BigDecimal endLbn) {
		this.endLbn = endLbn;
	}

	@Column(name = "P_PERIOD", length = 32)
	@XmlElement
	public String getPPeriod() {
		return PPeriod;
	}

	public void setPPeriod(final String PPeriod) {
		this.PPeriod = PPeriod;
	}

	@Column(name = "L1_EVENTS", precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getL1Events() {
		return l1Events;
	}

	public void setL1Events(final BigDecimal l1Events) {
		this.l1Events = l1Events;
	}

	@Column(name = "L2_EVENTS", precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getL2Events() {
		return l2Events;
	}

	public void setL2Events(final BigDecimal l2Events) {
		this.l2Events = l2Events;
	}

	@Column(name = "EF_EVENTS", precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getEfEvents() {
		return efEvents;
	}

	public void setEfEvents(final BigDecimal efEvents) {
		this.efEvents = efEvents;
	}

	@Column(name = "RECORDED_EVENTS", precision = 38, scale = 0)
	@XmlElement
	public BigDecimal getRecordedEvents() {
		return recordedEvents;
	}

	public void setRecordedEvents(final BigDecimal recordedEvents) {
		this.recordedEvents = recordedEvents;
	}

	@Column(name = "PARTITION_NAME")
	@XmlElement
	public String getPartitionName() {
		return partitionName;
	}

	public void setPartitionName(final String partitionName) {
		this.partitionName = partitionName;
	}

}
